package ar.com.yoamomibarrio.model;
// Generated 13/10/2013 23:06:13 by Hibernate Tools 3.2.1.GA



/**
 * BarrioPalabraClaveId generated by hbm2java
 */
public class BarrioPalabraClaveId  implements java.io.Serializable {


     private short idBarrio;
     private int idPalabraClave;

    public BarrioPalabraClaveId() {
    }

    public BarrioPalabraClaveId(short idBarrio, int idPalabraClave) {
       this.idBarrio = idBarrio;
       this.idPalabraClave = idPalabraClave;
    }
   
    public short getIdBarrio() {
        return this.idBarrio;
    }
    
    public void setIdBarrio(short idBarrio) {
        this.idBarrio = idBarrio;
    }
    public int getIdPalabraClave() {
        return this.idPalabraClave;
    }
    
    public void setIdPalabraClave(int idPalabraClave) {
        this.idPalabraClave = idPalabraClave;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BarrioPalabraClaveId) ) return false;
		 BarrioPalabraClaveId castOther = ( BarrioPalabraClaveId ) other; 
         
		 return (this.getIdBarrio()==castOther.getIdBarrio())
 && (this.getIdPalabraClave()==castOther.getIdPalabraClave());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdBarrio();
         result = 37 * result + this.getIdPalabraClave();
         return result;
   }   


}


