package ar.com.yoamomibarrio.model;
// Generated 13/10/2013 23:06:13 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Barrio generated by hbm2java
 */
public class Barrio  implements java.io.Serializable {


     private Short idBarrio;
     private String descripcion;
     private Set palabraClaveFaltantes = new HashSet(0);
     private Set barrioPalabraClaves = new HashSet(0);

    public Barrio() {
    }

	
    public Barrio(String descripcion) {
        this.descripcion = descripcion;
    }
    public Barrio(String descripcion, Set palabraClaveFaltantes, Set barrioPalabraClaves) {
       this.descripcion = descripcion;
       this.palabraClaveFaltantes = palabraClaveFaltantes;
       this.barrioPalabraClaves = barrioPalabraClaves;
    }
   
    public Short getIdBarrio() {
        return this.idBarrio;
    }
    
    public void setIdBarrio(Short idBarrio) {
        this.idBarrio = idBarrio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPalabraClaveFaltantes() {
        return this.palabraClaveFaltantes;
    }
    
    public void setPalabraClaveFaltantes(Set palabraClaveFaltantes) {
        this.palabraClaveFaltantes = palabraClaveFaltantes;
    }
    public Set getBarrioPalabraClaves() {
        return this.barrioPalabraClaves;
    }
    
    public void setBarrioPalabraClaves(Set barrioPalabraClaves) {
        this.barrioPalabraClaves = barrioPalabraClaves;
    }




}


