package ar.com.yoamomibarrio.model;
// Generated 13/10/2013 23:06:13 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Local generated by hbm2java
 */
public class Local  implements java.io.Serializable {


     private Long idLocal;
     private String razonSocial;
     private String direccion;
     private String telefono;
     private String telefono2;
     private String celular;
     private String paginaweb;
     private String mail;
     private String chat;
     private String redesocialesFb;
     private String redesocialesTw;
     private String redesocialesGm;
     private String foto;
     private String descripcion;
     private short idSubrubro;
     private short idBarrio;
     private Date fecha;
     private Set servicios = new HashSet(0);
     private Set localPalabraClaves = new HashSet(0);

    public Local() {
    }

	
    public Local(String razonSocial, String direccion, short idSubrubro, short idBarrio) {
        this.razonSocial = razonSocial;
        this.direccion = direccion;
        this.idSubrubro = idSubrubro;
        this.idBarrio = idBarrio;
    }
    public Local(String razonSocial, String direccion, String telefono, String telefono2, String celular, String paginaweb, String mail, String chat, String redesocialesFb, String redesocialesTw, String redesocialesGm, String foto, String descripcion, short idSubrubro, short idBarrio, Date fecha, Set servicios, Set localPalabraClaves) {
       this.razonSocial = razonSocial;
       this.direccion = direccion;
       this.telefono = telefono;
       this.telefono2 = telefono2;
       this.celular = celular;
       this.paginaweb = paginaweb;
       this.mail = mail;
       this.chat = chat;
       this.redesocialesFb = redesocialesFb;
       this.redesocialesTw = redesocialesTw;
       this.redesocialesGm = redesocialesGm;
       this.foto = foto;
       this.descripcion = descripcion;
       this.idSubrubro = idSubrubro;
       this.idBarrio = idBarrio;
       this.fecha = fecha;
       this.servicios = servicios;
       this.localPalabraClaves = localPalabraClaves;
    }
   
    public Long getIdLocal() {
        return this.idLocal;
    }
    
    public void setIdLocal(Long idLocal) {
        this.idLocal = idLocal;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getPaginaweb() {
        return this.paginaweb;
    }
    
    public void setPaginaweb(String paginaweb) {
        this.paginaweb = paginaweb;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getChat() {
        return this.chat;
    }
    
    public void setChat(String chat) {
        this.chat = chat;
    }
    public String getRedesocialesFb() {
        return this.redesocialesFb;
    }
    
    public void setRedesocialesFb(String redesocialesFb) {
        this.redesocialesFb = redesocialesFb;
    }
    public String getRedesocialesTw() {
        return this.redesocialesTw;
    }
    
    public void setRedesocialesTw(String redesocialesTw) {
        this.redesocialesTw = redesocialesTw;
    }
    public String getRedesocialesGm() {
        return this.redesocialesGm;
    }
    
    public void setRedesocialesGm(String redesocialesGm) {
        this.redesocialesGm = redesocialesGm;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public short getIdSubrubro() {
        return this.idSubrubro;
    }
    
    public void setIdSubrubro(short idSubrubro) {
        this.idSubrubro = idSubrubro;
    }
    public short getIdBarrio() {
        return this.idBarrio;
    }
    
    public void setIdBarrio(short idBarrio) {
        this.idBarrio = idBarrio;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set servicios) {
        this.servicios = servicios;
    }
    public Set getLocalPalabraClaves() {
        return this.localPalabraClaves;
    }
    
    public void setLocalPalabraClaves(Set localPalabraClaves) {
        this.localPalabraClaves = localPalabraClaves;
    }




}


