package ar.com.yoamomibarrio.model;
// Generated 13/10/2013 23:06:13 by Hibernate Tools 3.2.1.GA



/**
 * LocalPalabraClave generated by hbm2java
 */
public class LocalPalabraClave  implements java.io.Serializable {


     private LocalPalabraClaveId id;
     private Local local;

    public LocalPalabraClave() {
    }

    public LocalPalabraClave(LocalPalabraClaveId id, Local local) {
       this.id = id;
       this.local = local;
    }
   
    public LocalPalabraClaveId getId() {
        return this.id;
    }
    
    public void setId(LocalPalabraClaveId id) {
        this.id = id;
    }
    public Local getLocal() {
        return this.local;
    }
    
    public void setLocal(Local local) {
        this.local = local;
    }




}


