package ar.com.yoamomibarrio.model;
// Generated 13/10/2013 23:06:13 by Hibernate Tools 3.2.1.GA



/**
 * LocalPalabraClaveId generated by hbm2java
 */
public class LocalPalabraClaveId  implements java.io.Serializable {


     private short idLocal;
     private int idPalabraClave;

    public LocalPalabraClaveId() {
    }

    public LocalPalabraClaveId(short idLocal, int idPalabraClave) {
       this.idLocal = idLocal;
       this.idPalabraClave = idPalabraClave;
    }
   
    public short getIdLocal() {
        return this.idLocal;
    }
    
    public void setIdLocal(short idLocal) {
        this.idLocal = idLocal;
    }
    public int getIdPalabraClave() {
        return this.idPalabraClave;
    }
    
    public void setIdPalabraClave(int idPalabraClave) {
        this.idPalabraClave = idPalabraClave;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LocalPalabraClaveId) ) return false;
		 LocalPalabraClaveId castOther = ( LocalPalabraClaveId ) other; 
         
		 return (this.getIdLocal()==castOther.getIdLocal())
 && (this.getIdPalabraClave()==castOther.getIdPalabraClave());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdLocal();
         result = 37 * result + this.getIdPalabraClave();
         return result;
   }   


}


