package ar.com.yoamomibarrio.model;
// Generated 13/10/2013 23:06:13 by Hibernate Tools 3.2.1.GA



/**
 * LocalPromocionId generated by hbm2java
 */
public class LocalPromocionId  implements java.io.Serializable {


     private int idPromocion;
     private int idLocal;

    public LocalPromocionId() {
    }

    public LocalPromocionId(int idPromocion, int idLocal) {
       this.idPromocion = idPromocion;
       this.idLocal = idLocal;
    }
   
    public int getIdPromocion() {
        return this.idPromocion;
    }
    
    public void setIdPromocion(int idPromocion) {
        this.idPromocion = idPromocion;
    }
    public int getIdLocal() {
        return this.idLocal;
    }
    
    public void setIdLocal(int idLocal) {
        this.idLocal = idLocal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LocalPromocionId) ) return false;
		 LocalPromocionId castOther = ( LocalPromocionId ) other; 
         
		 return (this.getIdPromocion()==castOther.getIdPromocion())
 && (this.getIdLocal()==castOther.getIdLocal());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPromocion();
         result = 37 * result + this.getIdLocal();
         return result;
   }   


}


