package ar.com.yoamomibarrio.model;
// Generated 23/10/2013 20:10:56 by Hibernate Tools 3.2.1.GA



/**
 * LocalServicioId generated by hbm2java
 */
public class LocalServicioId  implements java.io.Serializable {


     private short idLocal;
     private short idServicio;

    public LocalServicioId() {
    }

    public LocalServicioId(short idLocal, short idServicio) {
       this.idLocal = idLocal;
       this.idServicio = idServicio;
    }
   
    public short getIdLocal() {
        return this.idLocal;
    }
    
    public void setIdLocal(short idLocal) {
        this.idLocal = idLocal;
    }
    public short getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(short idServicio) {
        this.idServicio = idServicio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LocalServicioId) ) return false;
		 LocalServicioId castOther = ( LocalServicioId ) other; 
         
		 return (this.getIdLocal()==castOther.getIdLocal())
 && (this.getIdServicio()==castOther.getIdServicio());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdLocal();
         result = 37 * result + this.getIdServicio();
         return result;
   }   


}


