package ar.com.yoamomibarrio.model;
// Generated 23/10/2013 20:10:56 by Hibernate Tools 3.2.1.GA



/**
 * LocalServicio generated by hbm2java
 */
public class LocalServicio  implements java.io.Serializable {


     private LocalServicioId id;

    public LocalServicio() {
    }

    public LocalServicio(LocalServicioId id) {
       this.id = id;
    }
   
    public LocalServicioId getId() {
        return this.id;
    }
    
    public void setId(LocalServicioId id) {
        this.id = id;
    }




}


