package ar.com.yoamomibarrio.model;
// Generated 13/10/2013 23:06:13 by Hibernate Tools 3.2.1.GA



/**
 * LocalMedioPago generated by hbm2java
 */
public class LocalMedioPago  implements java.io.Serializable {


     private LocalMedioPagoId id;

    public LocalMedioPago() {
    }

    public LocalMedioPago(LocalMedioPagoId id) {
       this.id = id;
    }
   
    public LocalMedioPagoId getId() {
        return this.id;
    }
    
    public void setId(LocalMedioPagoId id) {
        this.id = id;
    }




}


