package ar.com.yoamomibarrio.model;
// Generated 13/10/2013 23:06:13 by Hibernate Tools 3.2.1.GA



/**
 * MedioPago generated by hbm2java
 */
public class MedioPago  implements java.io.Serializable {


     private Short idPago;
     private String descripcion;
     private String icono;
     private String nota;

    public MedioPago() {
    }

	
    public MedioPago(String descripcion, String icono) {
        this.descripcion = descripcion;
        this.icono = icono;
    }
    public MedioPago(String descripcion, String icono, String nota) {
       this.descripcion = descripcion;
       this.icono = icono;
       this.nota = nota;
    }
   
    public Short getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(Short idPago) {
        this.idPago = idPago;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }




}


