package ar.com.yoamomibarrio.model;
// Generated 13/10/2013 23:06:13 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Seccion generated by hbm2java
 */
public class Seccion  implements java.io.Serializable {


     private Short idSeccion;
     private String descripcion;
     private Set rubros = new HashSet(0);

    public Seccion() {
    }

	
    public Seccion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Seccion(String descripcion, Set rubros) {
       this.descripcion = descripcion;
       this.rubros = rubros;
    }
   
    public Short getIdSeccion() {
        return this.idSeccion;
    }
    
    public void setIdSeccion(Short idSeccion) {
        this.idSeccion = idSeccion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getRubros() {
        return this.rubros;
    }
    
    public void setRubros(Set rubros) {
        this.rubros = rubros;
    }




}


