package ar.com.yoamomibarrio.model;
// Generated 13/10/2013 23:06:13 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Subrubro generated by hbm2java
 */
public class Subrubro  implements java.io.Serializable {


     private Short idSubrubro;
     private Rubro rubro;
     private String descripcion;
     private Set subrubroPalabraClaves = new HashSet(0);

    public Subrubro() {
    }

	
    public Subrubro(Rubro rubro, String descripcion) {
        this.rubro = rubro;
        this.descripcion = descripcion;
    }
    public Subrubro(Rubro rubro, String descripcion, Set subrubroPalabraClaves) {
       this.rubro = rubro;
       this.descripcion = descripcion;
       this.subrubroPalabraClaves = subrubroPalabraClaves;
    }
   
    public Short getIdSubrubro() {
        return this.idSubrubro;
    }
    
    public void setIdSubrubro(Short idSubrubro) {
        this.idSubrubro = idSubrubro;
    }
    public Rubro getRubro() {
        return this.rubro;
    }
    
    public void setRubro(Rubro rubro) {
        this.rubro = rubro;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getSubrubroPalabraClaves() {
        return this.subrubroPalabraClaves;
    }
    
    public void setSubrubroPalabraClaves(Set subrubroPalabraClaves) {
        this.subrubroPalabraClaves = subrubroPalabraClaves;
    }




}


