package ar.com.yoamomibarrio.model;
// Generated 13/10/2013 23:06:13 by Hibernate Tools 3.2.1.GA



/**
 * SubrubroPalabraClaveId generated by hbm2java
 */
public class SubrubroPalabraClaveId  implements java.io.Serializable {


     private short idSubrubro;
     private int idPalabraClave;

    public SubrubroPalabraClaveId() {
    }

    public SubrubroPalabraClaveId(short idSubrubro, int idPalabraClave) {
       this.idSubrubro = idSubrubro;
       this.idPalabraClave = idPalabraClave;
    }
   
    public short getIdSubrubro() {
        return this.idSubrubro;
    }
    
    public void setIdSubrubro(short idSubrubro) {
        this.idSubrubro = idSubrubro;
    }
    public int getIdPalabraClave() {
        return this.idPalabraClave;
    }
    
    public void setIdPalabraClave(int idPalabraClave) {
        this.idPalabraClave = idPalabraClave;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SubrubroPalabraClaveId) ) return false;
		 SubrubroPalabraClaveId castOther = ( SubrubroPalabraClaveId ) other; 
         
		 return (this.getIdSubrubro()==castOther.getIdSubrubro())
 && (this.getIdPalabraClave()==castOther.getIdPalabraClave());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdSubrubro();
         result = 37 * result + this.getIdPalabraClave();
         return result;
   }   


}


