package ar.com.yoamomibarrio.model;
// Generated 13/10/2013 23:06:13 by Hibernate Tools 3.2.1.GA



/**
 * SubrubroPalabraClave generated by hbm2java
 */
public class SubrubroPalabraClave  implements java.io.Serializable {


     private SubrubroPalabraClaveId id;
     private Subrubro subrubro;

    public SubrubroPalabraClave() {
    }

    public SubrubroPalabraClave(SubrubroPalabraClaveId id, Subrubro subrubro) {
       this.id = id;
       this.subrubro = subrubro;
    }
   
    public SubrubroPalabraClaveId getId() {
        return this.id;
    }
    
    public void setId(SubrubroPalabraClaveId id) {
        this.id = id;
    }
    public Subrubro getSubrubro() {
        return this.subrubro;
    }
    
    public void setSubrubro(Subrubro subrubro) {
        this.subrubro = subrubro;
    }




}


