package ar.com.yoamomibarrio.model;
// Generated 13/10/2013 23:06:13 by Hibernate Tools 3.2.1.GA



/**
 * UsuarioLocalId generated by hbm2java
 */
public class UsuarioLocalId  implements java.io.Serializable {


     private int idUsuario;
     private int idLocal;

    public UsuarioLocalId() {
    }

    public UsuarioLocalId(int idUsuario, int idLocal) {
       this.idUsuario = idUsuario;
       this.idLocal = idLocal;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdLocal() {
        return this.idLocal;
    }
    
    public void setIdLocal(int idLocal) {
        this.idLocal = idLocal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioLocalId) ) return false;
		 UsuarioLocalId castOther = ( UsuarioLocalId ) other; 
         
		 return (this.getIdUsuario()==castOther.getIdUsuario())
 && (this.getIdLocal()==castOther.getIdLocal());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUsuario();
         result = 37 * result + this.getIdLocal();
         return result;
   }   


}


